version: '3.9'
 
services:
  db:
    container_name: carmanagement
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: carmanagement
    ports:
      - 4444:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: